#used in main
MAP_ROWS= 50
MAP_COLUMNS= 50

FOOD_PER_TURN= 5
FOOD_VALUE= 1

BASE_CELL_NUMBER= 20
SPAWNED_CELL_FOOD= 5

#used in cell
FOOD_TO_MOVE= 0.025
#FOOD_TO_SPLIT= 5

MESSENGER_PROTEIN_NUMBER= 5
SECONDARY_MESSENGER_NUMBER= 0

#used in grid
PAC_MAN_MODE= False

USE_CUSTOM_MAP= False
CUSTOM_MAP_FILE= "custom_maps/canyon.json"


# #defaults
# #used in main
# MAP_ROWS= 52
# MAP_COLUMNS= 52

# FOOD_PER_TURN= 3
# FOOD_VALUE= 1

# BASE_CELL_NUMBER= 15
# SPAWNED_CELL_FOOD= 5

# #used in cell
# FOOD_TO_MOVE= 0.025
# FOOD_TO_SPLIT= 5

#MESSENGER_PROTEIN_NUMBER= 4

# #used in grid
# PAC_MAN_MODE= False

# USE_CUSTOM_MAP= True
# CUSTOM_MAP_FILE= "custom_maps/smileyface.json"